import { Platform, type TextStyle, type ViewStyle } from "react-native";

/**
 * Design SoT from /workspace/copilot-ui-polish/tokens.json
 * Light theme only. Aliases keep existing screens compiling.
 */
export const colors = {
  // Canonical SoT
  bgPage: "#F2F4F7",
  bgCard: "#FFFFFF",
  bgElevated: "#FFFFFF",
  bgMuted: "#EEF1F5",
  bgInput: "#F7F8FA",
  bgModalScrim: "rgba(15, 23, 42, 0.40)",
  bgSelection: "#E8F5F0",
  bgSelectionBar: "#3B82F6",
  bgSidebarActive: "#EBF2FF",
  textPrimary: "#1B2B4B",
  textSecondary: "#6B7A90",
  textTertiary: "#8A94A6",
  textInverse: "#FFFFFF",
  textLink: "#6B7A90",
  borderSubtle: "#E5E7EB",
  borderHairline: "#EEF0F3",
  divider: "#E8ECF1",
  accentBlue: "#3B82F6",
  accentBlueSoft: "#EBF2FF",
  incomeGreen: "#10B981",
  incomeGreenText: "#059669",
  incomeGreenBg: "#D1FAE5",
  overBudgetRed: "#EF4444",
  overBudgetRedSoft: "#FEE2E2",
  overBudgetCallout: "#FF5A5F",
  debtOrange: "#F59E0B",
  debtOrangeDot: "#FB923C",
  assetBlue: "#3B82F6",
  assetBlueDot: "#60A5FA",
  chartBudgetLine: "#9CA3AF",
  chartSpendLine: "#FF5A5F",
  chartDashGreen: "#34D399",
  tabActive: "#3B82F6",
  tabInactive: "#8A94A6",
  toggleOn: "#3B82F6",
  toggleOff: "#D1D5DB",
  segmentActiveBg: "#374151",
  segmentActiveText: "#FFFFFF",
  segmentInactiveBg: "transparent",
  segmentTrackBg: "#EEF1F5",
  pillBg: "#EEF2F7",
  pillText: "#4B5568",
  categoryPillBg: "#E8EEF6",
  sparkleBlue: "#60A5FA",
  sparkleHalo: "rgba(96, 165, 250, 0.25)",
  progressTrack: "#E5E7EB",
  progressFill: "#1B2B4B",
  danger: "#EF4444",
  warning: "#F59E0B",
  success: "#10B981",
  // Aliases used by existing screens / primitives
  bg: "#F2F4F7",
  card: "#FFFFFF",
  text: "#1B2B4B",
  primary: "#3B82F6",
  primarySoft: "#EBF2FF",
  primaryPressed: "#2563EB",
  accent: "#3B82F6",
  navy: "#1B2B4B",
  income: "#10B981",
  spend: "#1B2B4B",
  chipBg: "#EEF1F5",
  chipOn: "#1B2B4B",
  border: "#E5E7EB",
  overlay: "rgba(15, 23, 42, 0.40)",
  shadow: "rgba(27, 43, 75, 0.08)",
} as const;

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  screenPaddingX: 16,
  cardPadding: 16,
  cardGap: 12,
  sectionGap: 20,
  listRowHeight: 60,
  tabBarHeight: 56,
  headerHeight: 52,
} as const;

export const radius = {
  xs: 6,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  card: 18,
  modal: 20,
  pill: 999,
  sheet: 16,
  input: 10,
  rowSelected: 12,
} as const;

export const fontFamily = Platform.select({
  web: "Inter, -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  default: undefined,
});

export const type = {
  largeTitle: {
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: -0.4,
    lineHeight: 34,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  displayAmount: {
    fontSize: 36,
    fontWeight: "800",
    letterSpacing: -0.6,
    lineHeight: 42,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  heroAmount: {
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.45,
    lineHeight: 36,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  title1: {
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: -0.3,
    lineHeight: 28,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  title2: {
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: -0.2,
    lineHeight: 24,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  title3: {
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.1,
    lineHeight: 22,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  headline: {
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 20,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  body: {
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 20,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  bodyEmphasized: {
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 20,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  callout: {
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 18,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  subhead: {
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.textSecondary,
    fontFamily,
  } satisfies TextStyle,
  caption: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    lineHeight: 14,
    color: colors.textTertiary,
    fontFamily,
  } satisfies TextStyle,
  captionEmphasized: {
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 16,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  footnote: {
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    color: colors.textSecondary,
    fontFamily,
  } satisfies TextStyle,
  sectionLabel: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    lineHeight: 14,
    color: colors.textTertiary,
    fontFamily,
  } satisfies TextStyle,
  tabLabel: {
    fontSize: 10,
    fontWeight: "500",
    lineHeight: 12,
    color: colors.tabInactive,
    fontFamily,
  } satisfies TextStyle,
  amountList: {
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: -0.1,
    lineHeight: 20,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  moneyHero: {
    fontSize: 36,
    fontWeight: "800",
    letterSpacing: -0.6,
    lineHeight: 42,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
  money: {
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: -0.1,
    lineHeight: 20,
    color: colors.textPrimary,
    fontFamily,
  } satisfies TextStyle,
} as const;

export const shadow = {
  card: Platform.select<ViewStyle>({
    web: {
      boxShadow:
        "0 4px 16px rgba(27, 43, 75, 0.06), 0 1px 2px rgba(27, 43, 75, 0.04)",
    } as ViewStyle,
    ios: {
      shadowColor: "#1B2B4B",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
    },
    android: { elevation: 2 },
    default: {},
  }),
  modal: Platform.select<ViewStyle>({
    web: {
      boxShadow:
        "0 24px 64px rgba(15, 23, 42, 0.18), 0 8px 16px rgba(15, 23, 42, 0.08)",
    } as ViewStyle,
    ios: {
      shadowColor: "#0F172A",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.18,
      shadowRadius: 40,
    },
    android: { elevation: 12 },
    default: {},
  }),
  tabBar: Platform.select<ViewStyle>({
    web: {
      boxShadow: "0 -1px 0 rgba(27, 43, 75, 0.06)",
    } as ViewStyle,
    ios: {
      shadowColor: "#1B2B4B",
      shadowOffset: { width: 0, height: -1 },
      shadowOpacity: 0.06,
      shadowRadius: 0,
    },
    android: { elevation: 8 },
    default: {},
  }),
} as const;

export const layout = {
  screenPadding: spacing.screenPaddingX,
  cardPadding: spacing.cardPadding,
  sectionGap: spacing.sectionGap,
  maxContentWidth: 1100,
  maxContentWidthMobile: 720,
  listPaneRatio: 0.58,
  detailPaneRatio: 0.42,
  sidebarWidth: 220,
  desktopBreakpoint: 900,
  webContentPadding: 20,
} as const;

export const theme = {
  colors,
  spacing,
  radius,
  type,
  shadow,
  layout,
  fontFamily,
} as const;

export type Theme = typeof theme;
